spring.application.name=blindtest
server.port=4673

spring.datasource.url=jdbc:sqlite:data/blindtest.db?foreign_keys=on
spring.datasource.hikari.maximum-pool-size=1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
